from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1500, 550)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        spacerItem = QtWidgets.QSpacerItem(499, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.title_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(499, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.des_label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.des_label_2.setFont(font)
        self.des_label_2.setObjectName("des_label_2")
        self.horizontalLayout_2.addWidget(self.des_label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(499, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.distribution_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.distribution_label.setFont(font)
        self.distribution_label.setObjectName("distribution_label")
        self.horizontalLayout_6.addWidget(self.distribution_label)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setStyleSheet("QComboBox"
                                    "{"
                                    "background-color: white;"
                                    "}")
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(499, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.para_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.para_label.setFont(font)
        self.para_label.setObjectName("para_label")
        self.horizontalLayout_7.addWidget(self.para_label)
        self.mean_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.mean_lineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mean_lineEdit.setFont(font)
        self.mean_lineEdit.setObjectName("mean_lineEdit")
        self.horizontalLayout_7.addWidget(self.mean_lineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.formLayout_2.setLayout(7, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_7)
        spacerItem12 = QtWidgets.QSpacerItem(499, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.para_label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.para_label_2.setFont(font)
        self.para_label_2.setObjectName("para_label_2")
        self.horizontalLayout_3.addWidget(self.para_label_2)
        self.sd_lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.sd_lineEdit_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sd_lineEdit_2.setFont(font)
        self.sd_lineEdit_2.setObjectName("sd_lineEdit_2")
        self.horizontalLayout_3.addWidget(self.sd_lineEdit_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.formLayout_2.setLayout(9, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        spacerItem15 = QtWidgets.QSpacerItem(499, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.default_checkBox = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.default_checkBox.setFont(font)
        self.default_checkBox.setObjectName("default_checkBox")
        self.horizontalLayout_4.addWidget(self.default_checkBox)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.formLayout_2.setLayout(11, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        spacerItem18 = QtWidgets.QSpacerItem(499, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem18)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem19)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem20)
        self.back_Button = QtWidgets.QPushButton(Dialog)
        self.back_Button.setObjectName("back_Button")
        self.horizontalLayout_5.addWidget(self.back_Button)
        self.next_Button = QtWidgets.QPushButton(Dialog)
        self.next_Button.setObjectName("next_Button")
        self.horizontalLayout_5.addWidget(self.next_Button)
        spacerItem21 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem22)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Synthetic Data Generator"))
        self.title_label.setText(_translate("Dialog", "OMOP Common Data Model Generator"))
        self.des_label_2.setText(_translate("Dialog", "Customisation for Age"))
        self.distribution_label.setText(_translate("Dialog", "Distribution:"))
        self.comboBox.setItemText(0, _translate("age_rules", "  Normal distribution  "))
        self.comboBox.setItemText(1, _translate("age_rules", "  Binomial distribution  "))
        self.comboBox.setItemText(2, _translate("age_rules", "  Poisson distribution  "))
        self.para_label.setText(_translate("age_rules", "Mean age:"))
        self.para_label_2.setText(_translate("age_rules", "Standard distribution:"))
        self.default_checkBox.setText(_translate("age_rules", "Use the default settings (Normal Distribution, "
                                                              "Mean=40, SD=20)"))
        self.back_Button.setText(_translate("Dialog", "Back"))
        self.next_Button.setText(_translate("Dialog", "Next"))

