from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1500, 550)
        self.formLayout_2 = QtWidgets.QFormLayout(Dialog)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(490, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.title_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(490, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.des_label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.des_label_2.setFont(font)
        self.des_label_2.setObjectName("des_label_2")
        self.horizontalLayout_2.addWidget(self.des_label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(490, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.person_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.person_label.setFont(font)
        self.person_label.setObjectName("person_label")
        self.horizontalLayout_6.addWidget(self.person_label)
        self.person_lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.person_lineEdit_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.person_lineEdit_2.setFont(font)
        self.person_lineEdit_2.setObjectName("person_lineEdit_2")
        self.horizontalLayout_6.addWidget(self.person_lineEdit_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(490, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.specimen_label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.specimen_label_2.setFont(font)
        self.specimen_label_2.setObjectName("specimen_label_2")
        self.horizontalLayout_8.addWidget(self.specimen_label_2)
        self.specimen_lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.specimen_lineEdit_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.specimen_lineEdit_3.setFont(font)
        self.specimen_lineEdit_3.setObjectName("specimen_lineEdit_3")
        self.horizontalLayout_8.addWidget(self.specimen_lineEdit_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_8)
        spacerItem12 = QtWidgets.QSpacerItem(490, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.measurement_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.measurement_label.setFont(font)
        self.measurement_label.setObjectName("measurement_label")
        self.horizontalLayout_7.addWidget(self.measurement_label)
        self.measurement_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.measurement_lineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.measurement_lineEdit.setFont(font)
        self.measurement_lineEdit.setObjectName("measurement_lineEdit")
        self.horizontalLayout_7.addWidget(self.measurement_lineEdit)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_7)
        spacerItem15 = QtWidgets.QSpacerItem(490, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem15)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.observation_label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.observation_label_2.setFont(font)
        self.observation_label_2.setObjectName("observation_label_2")
        self.horizontalLayout_3.addWidget(self.observation_label_2)
        self.observation__lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.observation__lineEdit_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.observation__lineEdit_2.setFont(font)
        self.observation__lineEdit_2.setObjectName("observation__lineEdit_2")
        self.horizontalLayout_3.addWidget(self.observation__lineEdit_2)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        spacerItem18 = QtWidgets.QSpacerItem(490, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem18)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem19)
        self.default_checkBox = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.default_checkBox.setFont(font)
        self.default_checkBox.setObjectName("default_checkBox")
        self.horizontalLayout_4.addWidget(self.default_checkBox)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem20)
        self.formLayout.setLayout(13, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        spacerItem21 = QtWidgets.QSpacerItem(490, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(14, QtWidgets.QFormLayout.LabelRole, spacerItem21)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem22)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem23)
        self.back_Button = QtWidgets.QPushButton(Dialog)
        self.back_Button.setObjectName("back_Button")
        self.horizontalLayout_5.addWidget(self.back_Button)
        self.next_Button = QtWidgets.QPushButton(Dialog)
        self.next_Button.setObjectName("next_Button")
        self.horizontalLayout_5.addWidget(self.next_Button)
        spacerItem24 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem25)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Synthetic Data Generator"))
        self.title_label.setText(_translate("Dialog", "OMOP Common Data Model Generator"))
        self.des_label_2.setText(_translate("Dialog", "Customisation for the CSV File(s)"))
        self.person_label.setText(_translate("Dialog", "Number of Rows in Person Table:"))
        self.specimen_label_2.setText(_translate("Dialog", "Number of Rows in Specimen Table:"))
        self.measurement_label.setText(_translate("Dialog", "Number of Rows in Measurement Table:"))
        self.observation_label_2.setText(_translate("Dialog", "Number of Rows in Observation Table:"))
        self.default_checkBox.setText(_translate("Dialog", "Use 100 rows for each table"))
        self.back_Button.setText(_translate("Dialog", "Back"))
        self.next_Button.setText(_translate("Dialog", "Generate"))
